cmake_minimum_required(VERSION 3.16)
project(yurots LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
find_package(LibXml2 REQUIRED)
find_package(Boost REQUIRED COMPONENTS regex)
find_package(Threads REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(LUA REQUIRED lua5.1)
file(GLOB SOURCES CONFIGURE_DEPENDS "*.cpp")
add_executable(yurots ${SOURCES})
target_include_directories(yurots PRIVATE ${LIBXML2_INCLUDE_DIRS} ${LUA_INCLUDE_DIRS})
target_compile_options(yurots PRIVATE -include ${CMAKE_CURRENT_SOURCE_DIR}/compat.h -Wno-deprecated-declarations)
target_compile_definitions(yurots PRIVATE TLM_BUY_SELL TLM_SERVER_SAVE TLM_HOUSE_SYSTEM BDB_UTEVO_LUX WOLV_LOAD_NPC BD_HOUSE_WINDOW TR_ANTI_AFK ELEM_VIP_LIST TR_SUMMONS TRS_GM_INVISIBLE TLM_SKULLS_PARTY BRN_EXIVA SD_BURST_ARROW BDB_REPLACE_SPEARS BD_ITEM_LOOK SM_RELOAD_CONFIG JD_DEATH_LIST CT_EXANI_TERA CVS_DAY_CYCLE TJ_MONSTER_BLOOD JD_WANDS YUR_CVS_MODS YUR_ICE_RAPIER YUR_AOL YUR_LOGIN_QUEUE YUR_MULTIPLIERS YUR_BOH YUR_NPC_EXT YUR_GUILD_SYSTEM YUR_CMD_EXT YUR_ITEM_EXT YUR_ACT_EXT YUR_NO_MONSTER_HEAL YUR_PVP_ARENA YUR_RINGS_AMULETS YUR_CONFIG_CAP YUR_FIGHT_MODE YUR_READABLES YUR_LEARN_SPELLS YUR_HEAL_EXHAUST YUR_SHUTDOWN YUR_ROOKGARD YUR_LIGHT_ITEM YUR_CLEAN_MAP YUR_GM_LOOK YUR_HIGH_LEVELS YUR_PREMIUM_PROMOTION YUR_INVISIBLE YUR_DRAINS YUR_BUILTIN_AAC)
target_link_libraries(yurots PRIVATE ${LIBXML2_LIBRARIES} ${LUA_LIBRARIES} Boost::regex Threads::Threads)
